name: PVPBalance
main: PvpBalance.PvpBalance
version: 1.52
description:
            The Best plugin EVER
commands:
    PVPDebug:
    PVPVer:
    PVPInfo:
    polish:
    pvpgod:
    pvpstats:
    pvptop:
    party:
    effect:
    effecttype:
    effectspeed:
    effectcount:
    effectreset:
    effectheight:
    bet:
    acceptbet:
    acceptduel:
    endduel:
    play:
    leave:
    startevent: